import Layout from '@/components/Layout'
import Head from 'next/head'
import profilePic from '../../public/images/profile/dev3.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import Image from 'next/image'
import { DeveloperPic, LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import { ReactTyped } from "react-typed";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ophelie | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-start text-light w-full min-h-screen'>
      <div className='min-w-[50vw] px-10 pb-0 sm:px-0
                           rounded-lg backdrop-blur-md'>
      
        <Layout className='pt-0'>
          <div className='bg-light/20 rounded-2xl p-10 flex flex-row flex-wrap items-start justify-center w-full '>
           {/*<div className='absolute bottom-0 right-0 opacity-70'>
              <Image src={profilePic} alt="profilPic"  width={350}
                priority
                />
  </div> */}
            <div className=' flex flex-col items-center self-center'>
              <AnimatedText text="Hello, I'm Ophélie ! Nice to meet you" className="!text-8xl lg:!text-6xl !text-left"/>
             
              <div className='flex items-center self-start mt-2'>

                <ReactTyped className='my-4 font-semibold text-2xl ml-2'
                          strings={[
                            "I'm a software developer",
                            "I'm a web developer",
                            "I'm a full-stack developer",
                            "I'm an UI/UX designer",
                            "I do Kung Fu",
                            "I love singing"
                          ]}
                          typeSpeed={40}
                          backSpeed={50}
                          loop
                      />
              </div>
             
              {/* <div className='flex items-center self-start mt-2'>
                <Link 
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                  hover:bg-light hover:text-dark border border-solid border-transparent hover:boder-dark" 
                  download={true}
                  href="/dummy.pdf" target={"_blank"}>
                    Resume <LinkArrow className="w-6 ml-1"/>
                </Link>
                <Link href="mailto:ophelie.deschaux@gmail.com" target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >Contact</Link>
              </div>*/}
            </div>

          </div>
        </Layout>
        </div>
        
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <HireMe/>
        </div>
      </main>
    </>
  )
}
